### ISSUE TITLE
Customized Colors

### ISSUE THREAD

**Issue by Heinerion** [mechatroner/atom-rainbow-csv#1]
It would be nice, if you could add a possibility to switch color schemes.
Something like a theme for bright editors would be nice, as the predefined colors are hard to read on white / light gray background.

**Comment by mechatroner** [comment]
Sure, this option will be added at some point.

**Comment by Fran-Rg** [comment]
Please

**Comment by mechatroner** [comment]
I've just published the updated version 0.3.0. Highlighting colors can now be configured in the package settings!

**Comment by Kycko** [comment]
How can we change the background red color for line breaks? 🤔
(I'm using now Pulsar, the fork of Atom)
