### ISSUE TITLE
Run and Cancel buttons not visible

### ISSUE THREAD

**Issue by bileshg** [mechatroner/atom-rainbow-csv#3]
The Run and Cancel buttons are not visible when using a dark theme in Atom IDE. Please refer to the following screenshot.

![image](https://user-images.githubusercontent.com/17637482/58913651-43383a00-86e2-11e9-8e0e-0e5a0c54d09e.png)

**Comment by mechatroner** [comment]
Thanks for bug report! I fixed this in version 0.4.1
