### ISSUE TITLE
Color Not Always Organized Correctly

### ISSUE THREAD

**Issue by kr-hansen** [mechatroner/atom-rainbow-csv#5]
Some column coloring shows up as being off or odd.  At the bottom, the "Col 2: "col_name"" matches the color in settings, but this isn't true in the actual tsv.  For this example, Column 2 should be green (as seen in the bottom) and column 7 should be magenta.

Using macOS Mojave Version 10.14.5 and Atom 1.38.1 x64 with rainbow-csv 0.3.0.

<img width="1792" alt="Screen Shot 2019-06-18 at 2 42 48 PM" src="https://user-images.githubusercontent.com/15696062/59711088-6978d200-91d8-11e9-8e6a-5d99690eac9f.png">

**Comment by mechatroner** [comment]
Thank you for bug report! I just published version 0.4.1 which fixes this issue.
