### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getGrammar' of undefined

### ISSUE THREAD

**Issue by dllllb** [mechatroner/atom-rainbow-csv#6]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.4
**Thrown From**: [rainbow-csv](https://github.com/mechatroner/atom-rainbow-csv) package 0.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getGrammar' of undefined

```
At /Users/dmitri/.atom/packages/rainbow-csv/index.js:687

TypeError: Cannot read property 'getGrammar' of undefined
    at HTMLDivElement.start_rbql (/packages/rainbow-csv/index.js:687:50)
```

### Commands

```
  3x -0:23.5.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-csv-markdown 1.0.2 
git-time-machine 2.1.0 
Hydrogen 2.10.0 
language-latex 1.2.0 
language-markdown 0.37.0 
language-scala 1.1.10 
markdown-preview-enhanced 0.16.2 
pdf-view 0.71.0 
rainbow-csv 0.3.0 
split-diff 1.6.0 
```

**Comment by mechatroner** [comment]
Thanks! 
Actually I have no idea why is this happening. I've added some basic checks on null values, at least it won't fail like this. You can update the package to 0.3.1 and please let me know if it helped or not. Does it highlight proper csv files for you?

**Comment by dllllb** [comment]
Can't reproduce the error in 0.3.1, it is fixed I think.
